
/*------------------------------------------------------------------------
    File        : IDataAccessResource
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Notes       : Data Access Base - no behaviout defined
                  The Resource property name is unique within this interface 
                  This is managed by having them in the same directory                  
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using Pmfo.Core.Common.IResource from propath.

interface Pmfo.Core.DataLayer.IDataAccessResource inherits IResource:  
  
end interface.