
/*------------------------------------------------------------------------
    File        : IServiceDataAccess
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using Pmfo.Core.DataLayer.IDataAccessResource from propath.

interface Pmfo.Core.DataLayer.IServiceDataAccess inherits IDataAccessResource:  
    
end interface.