
/*------------------------------------------------------------------------
    File        : ValidationHookEventType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     :  
    Notes       : 
  ----------------------------------------------------------------------*/

enum Pmfo.Core.DataLayer.ValidationHookEventType :  

    define enum Begin 
                End.

end enum.