
/*------------------------------------------------------------------------
    File        : EntityRequestTypeEnum
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Notes       : 
  ----------------------------------------------------------------------*/

enum Pmfo.Core.BusinessLogic.EntityRequestTypeEnum :  

    define enum Read 
                Update 
                Action .

end enum.